server:
  port: 8200
spring:
  application:
    name: zuul_gateway
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8100/eureka
    registry-fetch-interval-seconds: 10
zuul:
  prefix: /api
  routes:
    item-service: /item/**
    search-service: /search/**
    upload_service:
      path: /upload/**
      service: upload_service
      strip-prefix: false
  ignored-services:
    - upload_service
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
ribbon:
  ConnectTimeout: 17000
  ReadTimeout: 17500
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0


